[package]
name = "starcoin-bridge-macros"
version = "0.1.0"
authors = ["Starcoin Contributors"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
once_cell = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
