[package]
name = "starcoin-bridge-config"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# Use Starcoin config utilities
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
anyhow = "1.0"
starcoin-config = { path = "../../config" }

