[package]
name = "test-cluster"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# Starcoin test helper from starcoin-vm1
starcoin-test-helper = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
